export enum Routes {
  demo = "demo",
  pricing = "pricing",
  themes = "themes",
  integrations = "integrations",
  customizations = "customizations",
  technology = "technology",
  requirements = "requirements",
  flightsModuleFeatures = "flights-module-features",
  hotelsModuleFeatures = "hotels-module-features",
  toursModuleFeatures = "tours-module-features",
  carsModuleFeatures = "cars-module-features",
  blogsModuleFeatures = "blog-module-features",
  cmsModuleFeatures = "cms-module-features",
  offersModuleFeatures = "offers-module-features",
  newsletterModuleFeatures = "newsletter-module-features",
  clients = "clients",
  blogs = "blog/",
  docs = "https://docs.phptravels.com/",
  contactUs = "contact-us",
  aboutUs = "about-us",
  theTeam = "the-team",
  jobs = "jobs",
  partners = "partners",
}
